pipeline {
    agent any

    stages {

	stage ('Validate Java') {
 	    steps {
		sh """
		cd DynamicDisplays
		mvn -B -DskipTests clean validate
		"""
	    }
	}

	stage ('Validate scripts') {
 	    steps {
		sh """
		cd DynamicDisplays
		./checkAllScripts.sh
		"""
	    }
	}
	
	stage ('Build') {
 	    steps {
		sh """
		cd DynamicDisplays
		mvn -B -DskipTests clean compile
		""" 
	    }
	}
	
	stage ('Unit Tests') {
 	    steps {
		sh """
		cd DynamicDisplays
		mvn -B test
		"""
	    }
	}
	
	stage ('Run Tests Part 1') {
 	    steps {
		sh """
		cd DynamicDisplays
		echo "----- Verify that hostname from JVM matches hostname from the OS -----"
		./compareHostNames.sh
		set +x		
		. ./setupEnvironment.sh

		echo "----- Testing that certain classes run -------------------------------"

		echo
		echo "======================================================================"
		echo "==========" gov.fnal.ppd.dd.util.nonguiUtils.JavaVersion 
		java gov.fnal.ppd.dd.util.nonguiUtils.JavaVersion 

		echo
		echo "======================================================================"
		echo "==========" gov.fnal.ppd.dd.util.nonguiUtils.PerformanceMonitor 
		java gov.fnal.ppd.dd.util.nonguiUtils.PerformanceMonitor 

		echo
		echo "======================================================================"
		echo "==========" gov.fnal.ppd.dd.util.nonguiUtils.VerifyURL 
		java gov.fnal.ppd.dd.util.nonguiUtils.VerifyURL https://dynamicdisplays.fnal.gov/borderA.php?url=https%3A%2F%2Fdynamicdisplays.fnal.gov%2Fabout.php

		echo
		echo "======================================================================"
		echo "==========" gov.fnal.ppd.dd.util.specific.TestAllChannels silent
		echo "Note: This is a check of whether or not all of the \"Approved\" channels are still viable"
		java gov.fnal.ppd.dd.util.specific.TestAllChannels silent

		echo
		echo "======================================================================"
		echo "==========" gov.fnal.ppd.dd.changer.ChannelCatalogFactory 
		java gov.fnal.ppd.dd.changer.ChannelCatalogFactory 

		echo
		echo "======================================================================"
		echo "==========" gov.fnal.ppd.dd.channel.MapOfChannels 
		java gov.fnal.ppd.dd.channel.MapOfChannels 
		"""
	    }
	}
	
	stage ('Run Tests Part 2') {
 	    steps {
		sh """

		cd DynamicDisplays
		set +x		
		. ./setupEnvironment.sh

		echo "----- Testing that more classes run -------------------------------"

		echo
		echo "======================================================================"
		echo "==========" gov.fnal.ppd.dd.db.DisplayUtilDatabase 
		java gov.fnal.ppd.dd.db.DisplayUtilDatabase 

		echo
		echo "======================================================================"
		echo "==========" gov.fnal.ppd.dd.db.GetDefaultContentForDisplay 
		java gov.fnal.ppd.dd.db.GetDefaultContentForDisplay 

		echo
		echo "======================================================================"
		echo "==========" gov.fnal.ppd.dd.util.specific.HasChannelSelector 
		java gov.fnal.ppd.dd.util.specific.HasChannelSelector 

		echo
		echo "======================================================================"
		echo "==========" gov.fnal.ppd.dd.util.specific.IsDisplayNode 
		java gov.fnal.ppd.dd.util.specific.IsDisplayNode 

		echo
		echo
		echo "======================================================================"
		echo "==========" gov.fnal.ppd.dd.util.specific.TranslateGITHashCodeToDate 
		java gov.fnal.ppd.dd.util.specific.TranslateGITHashCodeToDate 

		echo
		echo "======================================================================"
		echo "==========" gov.fnal.ppd.security.CheckHostName
		java gov.fnal.ppd.security.CheckHostName

		echo
		echo "======================================================================"
		echo "========= Testing that the PropertiesFile class runs"
		cp -p ../config/config.properties ../config/config.properties_hold
		java gov.fnal.ppd.dd.util.nonguiUtils.PropertiesFile
		ls -l ../config/config.properties ../config/config.properties_hold
		rm ../config/config.properties 
		mv ../config/config.properties_hold ../config/config.properties

		set -x
		"""
	    }
	}
    }
 }