pipeline {
    agent any

    stages {

	stage ('Validate Java') {
 	    steps {
		sh """
		cd DynamicDisplays
		mvn -B -DskipTests clean validate
		"""
	    }
	}

	stage ('Validate scripts') {
 	    steps {
		sh """
		cd DynamicDisplays
		./checkAllScripts.sh
		"""
	    }
	}
	
	stage ('Build') {
 	    steps {
		sh """
		cd DynamicDisplays
		mvn -B -DskipTests clean compile
		""" 
	    }
	}
	
	stage ('Unit Tests') {
 	    steps {
		sh """
		cd DynamicDisplays
		mvn -B test
		"""
	    }
	}
	
	stage ('Rudimentary Run Test Linux') {
 	    steps {
		sh """
		cd DynamicDisplays
		. ./setupJars.sh
		
		echo "Testing that the JavaVersion class runs"
		java gov.fnal.ppd.dd.util.nonguiUtils.JavaVersion
		
		echo "Testing that the PropertiesFile class runs"
		cp -p ../config/config.properties ../config/config.properties_hold
		java gov.fnal.ppd.dd.util.nonguiUtils.PropertiesFile
		ls -l ../config/config.properties ../config/config.properties_hold
		rm ../config/config.properties 
		mv ../config/config.properties_hold ../config/config.properties
		"""
	    }
	}
    }
 }