#!/bin/bash
#
# ddisplay:  Starts and stops an instance of a Dynamic Display
#
# Version: @(#) /etc/init.d/ddisplay 1.0
#
# description: Starts and stops an instance of a Dynamic Display
#

if [ -f /etc/init.d/functions ]
then
    . /etc/init.d/functions
else
    echo "ERROR ctri: could not find /etc/init.d/functions"
    exit -1
fi

pathadd() {
    if [ -d "$1" ] && [[ ":$PATH:" != *":$1:"* ]]; then
        PATH="${PATH:+"$PATH:"}$1"
    fi
}

start()
{
    # Need to start X here

    echo $"Starting Dynamic Display instance for screen $1"
    rm -f /home/DD/display_$1.pid
    
    pathadd /usr/local/bin

    /home/DD/runDisplayNode.sh $1 >& /var/log/DD/Display_${1}_`date +%Y-%m-%d_%T`.log &
    
    # echo $! > /home/DD/display_$1.pid
    pidof java > /home/DD/display_$1.pid
    
    return 0
}

stop()
{	
    echo $"Stopping Dynamic Display on screen $1"
    
    if [ -e /home/DD/display_$1.pid ]; then	
	kill `cat /home/DD/display_$1.pid`
	rm -f /home/DD/display_$1.pid
    fi
    
    return 0
}

restart()
{
    stop $1
    start $1
}

reload()
{
    stop $1
    start $1
}

case "$1" in
    start)
  	start 0
	# If you need to start more than one display, uncomment the following line (and all the others in the CASE statement)
	# start 1
	;;
    stop)
  	stop 0
	# stop 1
	;;
    restart)
  	restart 0
	# restart 1
	;;
    reload)
  	reload 0
	# reload 1
	;;
esac
